// -------------------------------------------------------------
// 
// File Name: C:\Users\TEMP\Desktop\mod\gm_untitled\M_PSK_Modulator_Baseband.v
// Created: 2024-06-19 20:11:11
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: M_PSK_Modulator_Baseband
// Source Path: gm_untitled/HDL_DUT/Subsystem/Subsystem/M-PSK Modulator Baseband
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module M_PSK_Modulator_Baseband
          (in0_0,
           in0_1,
           out0_re,
           out0_im);


  input   in0_0;  // boolean
  input   in0_1;  // boolean
  output  signed [6:0] out0_re;  // sfix7_En6
  output  signed [6:0] out0_im;  // sfix7_En6


  wire [0:1] in0;  // boolean [2]
  wire [1:0] constellationLUTaddress;  // ufix2
  wire signed [6:0] constellationLUT_t1_re [0:3];  // sfix7_En6 [4]
  wire signed [6:0] constellationLUT_t1_im [0:3];  // sfix7_En6 [4]


  assign in0[0] = in0_0;
  assign in0[1] = in0_1;

  assign constellationLUTaddress = {in0[0], in0[1]};

  assign constellationLUT_t1_re[0] = 7'sb0101101;
  assign constellationLUT_t1_re[1] = 7'sb1010011;
  assign constellationLUT_t1_re[2] = 7'sb0101101;
  assign constellationLUT_t1_re[3] = 7'sb1010011;
  assign constellationLUT_t1_im[0] = 7'sb0101101;
  assign constellationLUT_t1_im[1] = 7'sb0101101;
  assign constellationLUT_t1_im[2] = 7'sb1010011;
  assign constellationLUT_t1_im[3] = 7'sb1010011;
  assign out0_re = constellationLUT_t1_re[constellationLUTaddress];
  assign out0_im = constellationLUT_t1_im[constellationLUTaddress];

endmodule  // M_PSK_Modulator_Baseband

